"use client"

import { useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import { useDashboard } from "@/lib/dashboard-store"
import { useAuth } from "@/lib/auth-context"
import {
  FileText,
  Download,
  Printer,
  Share2,
  CheckCircle,
  AlertCircle,
  Clock,
  Euro,
  Leaf,
  Package,
  Building,
  Calendar,
  Loader2,
} from "lucide-react"

export default function ComplianceReportPage() {
  const { projectedTax, carbonIntensity, availableCredits, readinessScore, taxPrediction } = useDashboard()
  const { user } = useAuth()
  const [isGenerating, setIsGenerating] = useState(false)
  const [reportGenerated, setReportGenerated] = useState(false)

  const handleGenerateReport = async () => {
    setIsGenerating(true)
    
    // Simulate report generation
    await new Promise((resolve) => setTimeout(resolve, 2000))
    
    setIsGenerating(false)
    setReportGenerated(true)
    
    // Create and download a simple text report
    const reportContent = `
CBAM COMPLIANCE REPORT
Generated: ${new Date().toLocaleDateString("en-GB")}
Company: ${user?.companyName || "N/A"}

EXPORT DATA SUMMARY
-------------------
Product Type: ${taxPrediction.productType || "Steel"}
Export Tonnage: ${taxPrediction.tonnage || 1000} tonnes
Production Method: ${taxPrediction.productionMethod || "Blast Furnace"}
Destination: ${taxPrediction.destinationCountry || "Germany"}

CARBON EMISSIONS SUMMARY
------------------------
Carbon Intensity: ${carbonIntensity.toFixed(2)} tCO₂ per tonne
Total Embedded Emissions: ${((taxPrediction.tonnage || 1000) * carbonIntensity).toFixed(0)} tCO₂
Available Carbon Credits: ${availableCredits} tCO₂

ESTIMATED CBAM LIABILITY
------------------------
Projected Tax: €${projectedTax.toLocaleString()}
Readiness Score: ${readinessScore.toFixed(0)}%
Compliance Status: ${readinessScore >= 80 ? "Compliant" : readinessScore >= 60 ? "Partial" : "At Risk"}

---
This report is generated by CBAM-Bridge.
For questions, contact support@cbam-bridge.com
    `.trim()

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `cbam-compliance-report-${new Date().toISOString().split("T")[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getComplianceStatus = () => {
    if (readinessScore >= 80) return { label: "Compliant", variant: "default" as const, icon: CheckCircle, color: "text-green-500" }
    if (readinessScore >= 60) return { label: "Partial Compliance", variant: "secondary" as const, icon: Clock, color: "text-amber-500" }
    return { label: "At Risk", variant: "destructive" as const, icon: AlertCircle, color: "text-red-500" }
  }

  const status = getComplianceStatus()
  const StatusIcon = status.icon

  return (
    <div className="flex flex-col gap-6 p-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-bold text-foreground">Compliance Report</h1>
        <p className="text-muted-foreground">
          Generate and download your CBAM compliance documentation
        </p>
      </div>

      {/* Compliance Status */}
      <Card className="border-primary/30 bg-gradient-to-r from-primary/5 to-secondary/5">
        <CardContent className="flex flex-col items-start justify-between gap-6 p-6 sm:flex-row sm:items-center">
          <div className="flex items-center gap-4">
            <div className={`rounded-full p-3 ${status.color === "text-green-500" ? "bg-green-500/20" : status.color === "text-amber-500" ? "bg-amber-500/20" : "bg-red-500/20"}`}>
              <StatusIcon className={`h-8 w-8 ${status.color}`} />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-foreground">Compliance Status</h3>
              <p className="text-sm text-muted-foreground">
                {readinessScore >= 80
                  ? "Your exports meet EU CBAM requirements"
                  : readinessScore >= 60
                    ? "Some improvements needed for full compliance"
                    : "Urgent action required"}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right">
              <p className="text-sm text-muted-foreground">Readiness Score</p>
              <p className={`text-2xl font-bold ${status.color}`}>{readinessScore.toFixed(0)}%</p>
            </div>
            <Badge variant={status.variant} className="text-sm">
              {status.label}
            </Badge>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Report Preview */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              Report Preview
            </CardTitle>
            <CardDescription>Summary of your CBAM compliance data</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Export Data Summary */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <Package className="h-4 w-4" />
                Export Data Summary
              </div>
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Product Type</p>
                  <p className="text-lg font-semibold text-foreground capitalize">
                    {taxPrediction.productType || "Steel"}
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Export Tonnage</p>
                  <p className="text-lg font-semibold text-foreground">
                    {(taxPrediction.tonnage || 1000).toLocaleString()} tonnes
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Production Method</p>
                  <p className="text-lg font-semibold text-foreground capitalize">
                    {(taxPrediction.productionMethod || "blast_furnace").replace("_", " ")}
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Destination</p>
                  <p className="text-lg font-semibold text-foreground capitalize">
                    {taxPrediction.destinationCountry || "Germany"}
                  </p>
                </div>
              </div>
            </div>

            <Separator />

            {/* Carbon Emissions Summary */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <Leaf className="h-4 w-4" />
                Carbon Emissions Summary
              </div>
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Carbon Intensity</p>
                  <p className="text-lg font-semibold text-foreground">
                    {carbonIntensity.toFixed(2)} tCO₂/t
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Total Embedded Emissions</p>
                  <p className="text-lg font-semibold text-foreground">
                    {((taxPrediction.tonnage || 1000) * carbonIntensity).toFixed(0)} tCO₂
                  </p>
                </div>
                <div className="rounded-lg border border-border bg-muted/30 p-4">
                  <p className="text-sm text-muted-foreground">Available Credits</p>
                  <p className="text-lg font-semibold text-green-500">
                    {availableCredits} tCO₂
                  </p>
                </div>
              </div>
            </div>

            <Separator />

            {/* Estimated CBAM Liability */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <Euro className="h-4 w-4" />
                Estimated CBAM Liability
              </div>
              <div className="rounded-lg border border-primary/30 bg-gradient-to-r from-primary/5 to-primary/10 p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Projected Tax Amount</p>
                    <p className="text-3xl font-bold text-primary">€{projectedTax.toLocaleString()}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-sm text-muted-foreground">Readiness</p>
                    <Progress value={readinessScore} className="mt-2 h-2 w-24" />
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Actions Panel */}
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Generate Report</CardTitle>
              <CardDescription>Download your compliance documentation</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <Button
                className="w-full"
                size="lg"
                onClick={handleGenerateReport}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download className="mr-2 h-4 w-4" />
                    Generate Report
                  </>
                )}
              </Button>

              {reportGenerated && (
                <p className="text-center text-sm text-green-500">
                  Report downloaded successfully
                </p>
              )}

              <Separator />

              <div className="space-y-2">
                <Button variant="outline" className="w-full">
                  <Printer className="mr-2 h-4 w-4" />
                  Print Report
                </Button>
                <Button variant="outline" className="w-full">
                  <Share2 className="mr-2 h-4 w-4" />
                  Share Report
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Report Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2 text-muted-foreground">
                  <Building className="h-4 w-4" />
                  Company
                </span>
                <span className="font-medium text-foreground">{user?.companyName || "N/A"}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2 text-muted-foreground">
                  <Calendar className="h-4 w-4" />
                  Report Date
                </span>
                <span className="font-medium text-foreground">
                  {new Date().toLocaleDateString("en-GB")}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2 text-muted-foreground">
                  <FileText className="h-4 w-4" />
                  Format
                </span>
                <span className="font-medium text-foreground">TXT / PDF</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
